# Load data into APPLICATION table
LOAD DATA LOCAL INFILE 'APPLICATIONS.csv' 
INTO TABLE APPLICATION 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(APP_NAME,APP_DESCRIPTION,SIZE,CATEGORY_CODE,PRICE,CONTENT_RATING,
UPDATE_DATE,CURRENT_VERSION,AD_FREQ_PHR,RELEASED_DATE,DEVELOPER_ID,
APP_ENGAGE_TIME_PD,INAPP_PURCHASE,EDITOR_CHOICE,TYPE);

# Load data into REVIEW table
LOAD DATA LOCAL INFILE 'REVIEW.csv' 
INTO TABLE REVIEW 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(USER_ID,REVIEW_TEXT,REVIEW_DATE,RATING,RATING_DATE,APP_ID);

# Load data into DOWNLOAD table
LOAD DATA LOCAL INFILE 'DOWNLOADS.csv' 
INTO TABLE DOWNLOAD 
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(USER_ID,APP_ID,DOWNLOAD_DATE);
