# FREE APP DOWNLOADS BASED ON CATEGORY: 
# This stored procedure displays Total downloads of free apps per category.

DELIMITER //
CREATE PROCEDURE FREEAPP()
BEGIN 
SELECT CATEGORY, SUM(TOTAL_DOWNLOADS) 
FROM (
	SELECT A.APP_NAME,C.CATEGORY,COUNT(A.APP_NAME) AS TOTAL_DOWNLOADS 
	FROM APPLICATION AS A
	JOIN DOWNLOAD AS D ON A.APP_ID = D.APP_ID 
	JOIN CATEGORY AS C ON A.CATEGORY_CODE = C.CATEGORY_CODE
 	WHERE A.PRICE = 0 
	GROUP BY A.APP_ID) AS FREE_TAB
GROUP BY CATEGORY;
END //
DELIMITER ;
CALL FREEAPP();
