# FREE VS PAID APPS with AD: 
# This stored procedure gives the total number of free and paid apps which has ad’s and also their Cumulative ad’s per day

DELIMITER //
CREATE PROCEDURE AD_FREEVSPAID()
BEGIN
SELECT TYPE, COUNT(TYPE), SUM(AD_PER_DAY) 
FROM (
	SELECT A.APP_NAME,C.CATEGORY, AVG(A.AD_FREQ_PHR),AVG(A.APP_ENGAGE_TIME_PD),
	(AVG(A.AD_FREQ_PHR) * AVG(A.APP_ENGAGE_TIME_PD)) AS AD_PER_DAY, A.TYPE 
	FROM APPLICATION AS A
	JOIN DOWNLOAD AS D ON A.APP_ID = D.APP_ID 
	JOIN CATEGORY AS C ON A.CATEGORY_CODE = C.CATEGORY_CODE 
	WHERE (A.AD_FREQ_PHR <> 0) AND (A.APP_ENGAGE_TIME_PD <> 0)
 	GROUP BY A.APP_ID) AS INAPP_TAB 
GROUP BY TYPE;
END //
DELIMITER ;
CALL AD_FREEVSPAID();
