# REVIEW PER CATEGORY:
# This stored procedure is created which will give the Total review count per each Category and when calling the stored procedure, if we pass NULL all the categories will be displayed else only passed Category data will be displayed

DELIMITER //
CREATE PROCEDURE REVIEW_CAT(IN CAT VARCHAR(50))
BEGIN
IF CAT IS NULL THEN 
	SELECT CATEGORY, SUM(REVIEWS) 
	FROM (
		SELECT  APP_NAME, CATEGORY, COUNT(REVIEW_DATE) AS REVIEWS
		FROM APPLICATION JOIN REVIEW USING (APP_ID) JOIN CATEGORY USING (CATEGORY_CODE)
		GROUP BY APP_ID
		) AS REVIEW_TAB 
	GROUP BY (CATEGORY);
ELSE	 
	SELECT CATEGORY, SUM(REVIEWS) 
	FROM (
		SELECT  APP_NAME, CATEGORY, COUNT(REVIEW_DATE) AS REVIEWS
		FROM APPLICATION JOIN REVIEW USING (APP_ID) JOIN CATEGORY USING (CATEGORY_CODE)
		GROUP BY APP_ID
		)AS REVIEW_TAB 
	GROUP BY (CATEGORY) 
	HAVING CATEGORY=CAT;
END IF;
END //DELIMITER ;
CALL REVIEW_CAT(NULL);
