CREATE TABLE DOWNLOAD(
USER_ID BIGINT,
APP_ID  BIGINT,
DOWNLOAD_DATE   DATE NOT NULL,
PRIMARY KEY(USER_ID,APP_ID),
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
FOREIGN KEY (APP_ID) REFERENCES APPLICATION(APP_ID));
