CREATE TABLE REVIEW(
REVIEW_ID   BIGINT PRIMARY KEY  AUTO_INCREMENT,
USER_ID BIGINT NOT NULL,
REVIEW_TEXT VARCHAR(2000) NOT NULL,
REVIEW_DATE DATE,                   
RATING  DECIMAL(2,1)    DEFAULT 0,
RATING_DATE DATE,                   
APP_ID  BIGINT NOT NULL,
FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
CONSTRAINT CHK_RATING CHECK (RATING BETWEEN 0 AND 5),
FOREIGN KEY(APP_ID) REFERENCES APPLICATION(APP_ID));
