CREATE TABLE DEVELOPER(
DEVELOPER_ID BIGINT AUTO_INCREMENT PRIMARY KEY, 
DEVELOPER_NAME  VARCHAR(30) NOT NULL, WEBSITE VARCHAR(50), DEVELOPER_EMAIL VARCHAR(30) NOT NULL,
DEVELOPER_COUNTRY   VARCHAR(20));
