# CR_VIEW: It  is created to display Application Name, Category, Content Rating, and Total downloads per application 
CREATE VIEW CR_VIEW AS (
	SELECT A.APP_NAME, C.CATEGORY, A.CONTENT_RATING,
	COUNT(D.DOWNLOAD_DATE) AS TOTAL_DOWNLOADS
	FROM APPLICATION AS A
	JOIN DOWNLOAD AS D ON A.APP_ID = D.APP_ID 
	JOIN CATEGORY AS C ON A.CATEGORY_CODE = C.CATEGORY_CODE
	GROUP BY A.APP_ID);
