# DOWNLOADS_VIEW: It  has Application Name, Category, Total Downloads per Application information.
CREATE VIEW DOWNLOADS_VIEW AS (
	SELECT APP_NAME,CATEGORY,COUNT(APP_NAME) AS "TOTAL_DOWNLOADS" 
	FROM APPLICATION 
	JOIN download USING (APP_ID) 
	JOIN CATEGORY USING (CATEGORY_CODE) 
	GROUP BY APP_ID);
