# FREEAPP_VIEW: It has information about Application Name, Category, Total Downloads per application only for free applications.
CREATE OR REPLACE VIEW FREEAPP_VIEW AS (
	SELECT A.APP_NAME, C.CATEGORY,COUNT(A.APP_NAME) AS TOTAL_DOWNLOADS 
	FROM APPLICATION  AS A
	JOIN DOWNLOAD AS DOWNLOAD ON A.APP_ID = D.APP_ID 
	JOIN CATEGORY AS C ON A.CATEGORY_CODE = C.CATEGORY_CODE
	WHERE A.PRICE = 0 
	GROUP BY A.APP_ID);
